[package]
name = "baseline"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
otils = { path = "../otils" }
clap = { version = "4.5.4", features = ["derive"] }

[package.metadata.fortanix-sgx]
stack-size=0x400000
heap-size=0x100000000
threads=9
